name: Backend-Workflow

on:
    push:
      branches: ["main"]
      paths: backend
    pull_request:
      branches: ["main"]
      paths: backend

jobs:
  backend-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      id: login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build Docker Image
      run: docker compose -f docker-compose.example.yaml build

    - name: Push Docker Image
      run: docker compose -f docker-compose.example.yaml push
    
    - name: Update Server
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.ECS_HOST }}
        user: ${{ secrets.ECS_USERNAME }}
        pass: ${{ secrets.ECS_PASSWORD }}
        run: sudo docker compose down ; sudo docker compose pull ; sudo docker compose up -d
